### PR TITLE
Mehul/faq page/#168 faqs

### PR DESCRIPTION
**Pull request by MehulKChaudhari**
This PR serves a FAQ page. 

desktop view:
image
image

mobile view: 
image
image

### CODE REVIEW

**Comment by sushilburagute** [comment]
@MehulKChaudhari can you please remove the checkbox option?

**Review by sushilburagute — APPROVED** [review]
Everything checks out. Things are working as intended on my dev environment. 

I think we should create a separate component for the faq card because the complexity for the card is now way more.

**Comment by MehulKChaudhari** [comment]
> Everything checks out. Things are working as intended on my dev environment.
> 
> I think we should create a separate component for the faq card because the complexity for the card is now way more.

Yeah we can, but had a card component that matches with UI and we have to just make it a little reusable so that's fine, Like we won't be adding Faq page again and again, we will just add questions So I don't think as need but we can do it

**Comment by MehulKChaudhari** [comment]
> @MehulKChaudhari a couple of UI changes:
> 
> * The checkbox icon shouldn't be there.
> * The title for the Headings of the FAQs should be white. Because the ratio of the color palette is maintained.

* That's not a checkbox, it's just a circle to match the UI.  Please let me know we add anything else there. 
* Done

**Comment by prerana1821** [comment]
Hey @MehulKChaudhari,
Awesome work, I too have checked it. Everything is working as required

**Comment by MehulKChaudhari** [comment]
> Hey @MehulKChaudhari,
> Awesome work, I too have checked it. Everything is working as required

Thanks for the review :)

**Review by sohamsshah — APPROVED** [review]
LGTM @MehulKChaudhari !
Amazing work 💯

**Comment by MehulKChaudhari** [comment]
> LGTM @MehulKChaudhari !
> Amazing work

Thanks for the review. :))

**Pull request merged**
