### PR TITLE
404 page

### PR DESCRIPTION
**Pull request by SAYUK09**
# Closes #<CORRESPONDING ISSUE NUMBER>

### Changes

- Created a `404` page.

### Flags

- File Structure (`assests/svgs`)

#### Desktop View
image

#### Mobile View
image

### Related Issues
- Issue #<NUMBER>
- Pull Request #<NUMBER>

### Author Checklist
- [x] Vital features and changes captured in unit and/or integration tests
- [ ] Extend the documentation, if necessary
- [x] Merging to `main` from `fork:sayuri/404`

### CODE REVIEW

**Review by sohamsshah — APPROVED** [review]
LGTM

**Comment by MehulKChaudhari** [comment]
Screenshot from 2021-07-04 13-07-42


Please look into the scrolling issue. align the `Click here to go back home` in the center. And make it a button instead and give gap between link and text.

**Comment by sohamsshah** [comment]
Please create a new issue for the same :)

**Comment by SAYUK09** [comment]
> Screenshot from 2021-07-04 13-07-42
> 
> Please look into the scrolling issue. align the `Click here to go back home` in the center. And make it a button instead and give gap between link and text.

Thanks for pointing that out.
The scrolling issue has been taken care of.
Regarding `center-alignment` , will discuss the design with @sushilburagute and make the necessary changes.
Thank you.

**Pull request merged**
